version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_app
    env_file: .env
    ports:
      - "8000:8000"   # Пробрасываем порт для Swagger
    volumes:
      - ./app:/app/app
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    image: nginx:latest
    container_name: ml_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ml_rabbit
    restart: on-failure
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # Основной порт RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  database:
    image: postgres:14
    container_name: ml_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ml_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
